default_stages: [commit, push]
repos:
  - repo: https://github.com/timothycrosley/isort
    rev: 5.7.0
    hooks:
      - id: isort
        exclude: (^generated/)

  - repo: https://github.com/python/black
    rev: 20.8b1
    hooks:
      - id: black
        exclude: (^generated/)

  - repo: https://github.com/PyCQA/flake8
    rev: 3.8.4
    hooks:
      - id: flake8
        exclude: (^generated/)

  - repo:  https://github.com/pre-commit/mirrors-mypy
    rev: v0.800
    hooks:
      - id: mypy
        additional_dependencies:
          - tokenize-rt==3.2.0
          - sqlalchemy-stubs==v0.4
        exclude: (^generated/)

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-byte-order-marker
        exclude: (^generated/)
      - id: check-case-conflict
        exclude: (^generated/)
      - id: trailing-whitespace
        exclude: (^generated/)
      - id: end-of-file-fixer
        exclude: (^generated/)
      - id: no-commit-to-branch
        args: ["--branch", "master"]
        exclude: (^generated/)
