"""INIT TABLES

Revision ID: 559813223f80
Revises:
Create Date: 2021-10-11 17:30:15.738069

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "559813223f80"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bitcoin",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("open", sa.Float(), nullable=False),
        sa.Column("high", sa.Float(), nullable=False),
        sa.Column("low", sa.Float(), nullable=False),
        sa.Column("volume", sa.Float(), nullable=False),
        sa.Column("change", sa.Float(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_bitcoin_date"), "bitcoin", ["date"], unique=False)
    op.create_table(
        "firms",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("trading_fee", sa.Float(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_firms_name"), "firms", ["name"], unique=False)
    op.create_table(
        "tickers",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "stock_type",
            sa.Enum("STOCK", "ETF", name="stocktype", native_enum=False),
            nullable=False,
        ),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("ticker", sa.String(length=255), nullable=False),
        sa.Column(
            "currency",
            sa.Enum("USD", "KRW", name="currency", native_enum=False),
            nullable=False,
        ),
        sa.Column("firm_id", sa.Integer(), nullable=True),
        sa.Column("fee", sa.Float(), nullable=False),
        sa.Column("tax", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["firm_id"],
            ["firms.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "bonds",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("ticker_id", sa.Integer(), nullable=True),
        sa.Column("stock_type", sa.String(length=255), nullable=False),
        sa.Column("adj_close", sa.Float(), nullable=False),
        sa.Column("close", sa.Float(), nullable=False),
        sa.Column("high", sa.Float(), nullable=False),
        sa.Column("low", sa.Float(), nullable=False),
        sa.Column("open", sa.Float(), nullable=False),
        sa.Column("volume", sa.BigInteger(), nullable=False),
        sa.Column("date_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("currency", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(
            ["ticker_id"],
            ["tickers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "ticker_id", "date_time", name="uix_bond_date_time_ticker_id"
        ),
    )
    op.create_index(
        "ix_bond_date_time_ticker_id",
        "bonds",
        [sa.text("date_time DESC"), "ticker_id"],
        unique=False,
    )
    op.create_table(
        "prices",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("ticker_id", sa.Integer(), nullable=True),
        sa.Column("adj_close", sa.Float(), nullable=False),
        sa.Column("close", sa.Float(), nullable=False),
        sa.Column("high", sa.Float(), nullable=False),
        sa.Column("low", sa.Float(), nullable=False),
        sa.Column("open", sa.Float(), nullable=False),
        sa.Column("volume", sa.BigInteger(), nullable=False),
        sa.Column("date_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "currency",
            sa.Enum("USD", "KRW", name="currency", native_enum=False),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["ticker_id"],
            ["tickers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "ticker_id", "date_time", name="uix_stock_date_time_ticker_id"
        ),
    )
    op.create_index(
        "ix_stock_date_time_ticker_id",
        "prices",
        ["ticker_id", sa.text("date_time DESC")],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_stock_date_time_ticker_id", table_name="prices")
    op.drop_table("prices")
    op.drop_index("ix_bond_date_time_ticker_id", table_name="bonds")
    op.drop_table("bonds")
    op.drop_table("tickers")
    op.drop_index(op.f("ix_firms_name"), table_name="firms")
    op.drop_table("firms")
    op.drop_index(op.f("ix_bitcoin_date"), table_name="bitcoin")
    op.drop_table("bitcoin")
    # ### end Alembic commands ###
