"""add stock assets

Revision ID: 5e57e6fc5e0b
Revises: 8f10cb2ccfc3
Create Date: 2021-10-24 19:56:18.680298

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "5e57e6fc5e0b"
down_revision = "8f10cb2ccfc3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stock_assets",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("ticker_id", sa.Integer(), nullable=True),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("purchase_price", sa.Float(), nullable=False),
        sa.Column("sell_price", sa.Float(), nullable=True),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column(
            "currency",
            sa.Enum("USD", "KRW", name="currency", native_enum=False),
            nullable=False,
        ),
        sa.Column("purchased_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("sold_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["ticker_id"],
            ["tickers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("stock_assets")
    # ### end Alembic commands ###
