"""Add name to ticker

Revision ID: 7f10d5023365
Revises: 8484b11f633f
Create Date: 2021-10-05 00:22:02.144982

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7f10d5023365"
down_revision = "8484b11f633f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tickers", sa.Column("name", sa.String(length=255), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tickers", "name")
    # ### end Alembic commands ###
