"""create bitcoin table

Revision ID: 845650b96c82
Revises:
Create Date: 2021-03-11 16:00:45.876498

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "845650b96c82"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bitcoin",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("open", sa.Float(), nullable=False),
        sa.Column("high", sa.Float(), nullable=False),
        sa.Column("low", sa.Float(), nullable=False),
        sa.Column("volume", sa.Float(), nullable=False),
        sa.Column("change", sa.Float(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_bitcoin_date"), "bitcoin", ["date"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_bitcoin_date"), table_name="bitcoin")
    op.drop_table("bitcoin")
    # ### end Alembic commands ###
