"""add deleted_at

Revision ID: 8f10cb2ccfc3
Revises: 559813223f80
Create Date: 2021-10-16 20:21:42.072055

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "8f10cb2ccfc3"
down_revision = "559813223f80"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "firms",
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "tickers",
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tickers", "deleted_at")
    op.drop_column("firms", "deleted_at")
    # ### end Alembic commands ###
