"""Add fee, tax columns

Revision ID: b17069a2f80c
Revises: da572e185607
Create Date: 2021-10-04 14:37:32.438136

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b17069a2f80c"
down_revision = "da572e185607"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tickers", sa.Column("fee", sa.Float(), nullable=False))
    op.add_column("tickers", sa.Column("tax", sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tickers", "tax")
    op.drop_column("tickers", "fee")
    # ### end Alembic commands ###
