"""create bond

Revision ID: da572e185607
Revises: ec04950c7270
Create Date: 2021-10-04 13:06:10.413195

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "da572e185607"
down_revision = "ec04950c7270"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "firms",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(255), nullable=False),
        sa.Column("trading_fee", sa.Float(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_firms_name"), "firms", ["name"], unique=False)
    op.create_table(
        "tickers",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("ticker", sa.String(length=255), nullable=False),
        sa.Column("firm_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["firm_id"],
            ["firms.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "bonds",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("ticker_id", sa.Integer(), nullable=True),
        sa.Column("stock_type", sa.String(length=255), nullable=False),
        sa.Column("adj_close", sa.Float(), nullable=False),
        sa.Column("close", sa.Float(), nullable=False),
        sa.Column("high", sa.Float(), nullable=False),
        sa.Column("low", sa.Float(), nullable=False),
        sa.Column("open", sa.Float(), nullable=False),
        sa.Column("volume", sa.BigInteger(), nullable=False),
        sa.Column("date_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("currency", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(
            ["ticker_id"],
            ["tickers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "ticker_id", "date_time", name="uix_date_time_ticker_id"
        ),
    )
    op.create_index(
        "ix_date_time_ticker_id",
        "bonds",
        [sa.text("date_time DESC"), "ticker_id"],
        unique=False,
    )
    op.add_column("prices", sa.Column("adj_close", sa.Float(), nullable=False))
    op.add_column(
        "prices",
        sa.Column("date_time", sa.DateTime(timezone=True), nullable=False),
    )
    op.add_column(
        "prices",
        sa.Column("stock_type", sa.String(length=255), nullable=False),
    )
    op.add_column(
        "prices", sa.Column("ticker_id", sa.Integer(), nullable=True)
    )
    op.drop_index("ix_date_name", table_name="prices")
    op.drop_index("ix_date_ticker", table_name="prices")
    op.create_index(
        "ix_date_time_ticker_id",
        "prices",
        ["ticker_id", sa.text("date_time DESC")],
        unique=False,
    )
    op.create_unique_constraint(
        "uix_date_time_ticker_id", "prices", ["ticker_id", "date_time"]
    )
    op.create_foreign_key(None, "prices", "tickers", ["ticker_id"], ["id"])
    op.drop_column("prices", "adjclose")
    op.drop_column("prices", "name")
    op.drop_column("prices", "date")
    op.drop_column("prices", "ticker")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "prices",
        sa.Column("ticker", mysql.VARCHAR(length=255), nullable=False),
    )
    op.add_column("prices", sa.Column("date", sa.DATE(), nullable=False))
    op.add_column(
        "prices", sa.Column("name", mysql.VARCHAR(length=255), nullable=False)
    )
    op.add_column(
        "prices", sa.Column("adjclose", mysql.FLOAT(), nullable=False)
    )
    op.drop_constraint(None, "prices", type_="foreignkey")
    op.drop_constraint("uix_date_time_ticker_id", "prices", type_="unique")
    op.drop_index("ix_date_time_ticker_id", table_name="prices")
    op.create_index("ix_date_ticker", "prices", ["date", "name"], unique=False)
    op.create_index("ix_date_name", "prices", ["date", "name"], unique=False)
    op.drop_column("prices", "ticker_id")
    op.drop_column("prices", "stock_type")
    op.drop_column("prices", "date_time")
    op.drop_column("prices", "adj_close")
    op.drop_index("ix_date_time_ticker_id", table_name="bonds")
    op.drop_table("bonds")
    op.drop_table("tickers")
    op.drop_index(op.f("ix_firms_name"), table_name="firms")
    op.drop_table("firms")
    # ### end Alembic commands ###
